import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "./Components/ShadcnComp/components/ui/sonner";
import { ThemeProvider } from "./Components/ShadcnComp/components/theme-provider";
import { createContext, useState } from "react";
import { Context } from "./Context";
import Navbar from "./Components/Navbar/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="en">
      <body className={poppins.className}>

        <Toaster closeButton richColors />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <Context>
            <Navbar />
            {children}
          </Context>


        </ThemeProvider>

      </body>
    </html >
  );
}
